### PR TITLE
Better support for ARM/M1/Apple Silicon

### PR DESCRIPTION
**Pull request by bombsimon**
## Changes

- Support more than one installation of `brew` - don't rely on `$PATH` or defaults, use `buildkite_agent_brew_dir `.

This use case is probably not that uncommon since a lot of things still needs to be emulated/run with Rosetta 2 making you install two versions of `brew`.

## Verification

* Run the playbook on a M1 Mac with `brew` installed both in `/opt/homebrew` for arm and `/usr/local` (to support Rosetta 2/Intel installations).

---

Sorry for the messy PR. I was trying to address a bunch of issues but let's fix the linting in #65 and have this PR only address which `brew` to invoke when multiple is installed. I also created #66 to resolve the group issues I had that made this PR messy.

### CODE REVIEW

**Comment by bombsimon** [comment]
I'm once again stuck in the workflow. Running `yamlfmt` (with `ci.sh`) will add an indentation for the whole file (since it's a list I think?) but after doing so, `yamllint` will complain about bad indentation. Didn't change any `.yamllint` configuration since I wanted to hear what your suggested solution would be.

~~Also, this is a really minor thing, haven't added anything to the `CHANGELOG` yet, please let me know if you want me to do this.~~

EDIT: Seems to be addressed in #65, will wait for that and rebase.

**Comment by bombsimon** [comment]
Also converting this to draft since I found a few other things which I missed in this (and the previous) PR. To fully support Apple M1 and installations under `/opt/homebrew`, we also need to be able to configure the user group. This is hardcoded for all platforms right now, do you mind me making it configurable for all of them? I guess more options won't harm if we keep sensible defaults. Something like this is what I had in mind:

```diff
diff --git a/defaults/main.yml b/defaults/main.yml
index a211f7f..0c1c320 100644
--- a/defaults/main.yml
+++ b/defaults/main.yml
@@ -2,6 +2,10 @@
 # core
 buildkite_agent_username: 'buildkite-agent'
 buildkite_agent_user_description: 'Runs BuildKite jobs. See https://buildkite.com/docs/agent/v3/.'
+buildkite_agent_user_group:
+  Darwin: 'wheel'
+  Debian: '{{ buildkite_agent_username }}'
+  Windows: 'Administrators'
 buildkite_agent_conf_dir:  # https://github.com/buildkite/agent/blob/master/clicommand/agent_start.go#L100
   Darwin: '{{ buildkite_agent_brew_dir }}/etc/buildkite-agent'
   Debian: '/etc/buildkite-agent'
diff --git a/tasks/install-on-Darwin.yml b/tasks/install-on-Darwin.yml
index 6c8e489..19a4cf6 100644
--- a/tasks/install-on-Darwin.yml
+++ b/tasks/install-on-Darwin.yml
@@ -23,7 +23,7 @@
     dest: '{{ buildkite_agent_conf_dir[ansible_os_family] }}/buildkite-agent.cfg'
     mode: '0400'
     owner: '{{ buildkite_agent_username }}'
-    group: 'wheel'
+    group: '{{ buildkite_agent_user_group[ansible_os_family] }}'
   notify:
     - 'restart-darwin-buildkite'
 
@@ -33,7 +33,7 @@
     dest: '{{ buildkite_agent_hooks_dir[ansible_os_family] }}/environment'
     mode: '0444'
     owner: '{{ buildkite_agent_username }}'
-    group: 'wheel'
+    group: '{{ buildkite_agent_user_group }}'
   when: 'buildkite_agent_load_bash_profile'
   notify:
     - 'restart-darwin-buildkite'
diff --git a/tasks/install-on-Debian.yml b/tasks/install-on-Debian.yml
index c9a32f6..ccfcdbb 100644
--- a/tasks/install-on-Debian.yml
+++ b/tasks/install-on-Debian.yml
@@ -45,7 +45,7 @@
     src: "buildkite-agent.cfg.j2"
     dest: "{{ buildkite_agent_conf_dir[ansible_os_family] }}/buildkite-agent.cfg"
     owner: "{{ buildkite_agent_username }}"
-    group: "{{ buildkite_agent_username }}"
+    group: '{{ buildkite_agent_user_group[ansible_os_family] }}'
     mode: "0600"
   notify:
     - restart-systemd-buildkite
diff --git a/tasks/install-on-Windows.yml b/tasks/install-on-Windows.yml
index 371c254..851ed2f 100644
--- a/tasks/install-on-Windows.yml
+++ b/tasks/install-on-Windows.yml
@@ -29,7 +29,7 @@
 
 - name: grant administrator privileges to user
   win_group_membership:
-    name: Administrators
+    name: '{{ buildkite_agent_user_group[ansible_os_family] }}'
     members:
       - "{{ buildkite_agent_username }}"
     state: "{{ 'present' if buildkite_agent_windows_grant_admin else 'absent' }}"
```

What do you think?

**Comment by PaulSonOfLars** [comment]
As you've already notced, I've re-linted the repo, which should hopefully make your PR easier and avoid the extra friction. 

I'm of the opinion that any new feature should go into changelog, especially given that this is a helpful addition :)

**Comment by bombsimon** [comment]
I rebased and squashed my mess, updated the `CHANGELOG`.

This partly fixes my issue of running multiple instances of `brew`. The problem is that there's still no support for this with the `homebrew_tap` target, see [this issue](https://github.com/ansible-collections/community.general/issues/1660) (closed today but I just added a comment).

I currently solve this by tapping the repository manually with my preferred `brew`. However, one could argue that this PR itself is useless since with only one installation of `brew`, this is not an issue and with multiple versions like I have, the user needs to add the tap manually. What do you think, should I add a manual tap step instead of the current `homebrew_tap` target, should I just close this PR or should we leave this as is with some kind of semi support and wait for upstream?

**Comment by Helcaraxan** [comment]
Hello @bombsimon. I agree with your analysis as to the usefulness of this PR relative to the upstream support for two `brew` installations. It seems that the upstream [asked you](https://github.com/ansible-collections/community.general/issues/1660#issuecomment-767812638) to create a new issue for supporting two separate installations. I'd reckon it's worth following up on that request and see what the reaction is. In the meantime we can hold this PR in its current state. It's unlikely to go stale anytime soon. :)

**Comment by bombsimon** [comment]
@Helcaraxan Thanks for your response!

I'll create a new issue and maybe a PR upstream regarding specifying path for `brew_tap` as well. Let's see how that pans out but when we support multiple brews natively we can take a new look at this issue.

**Review by filipVisko — APPROVED** [review]
Apologies for the delay here!

**Pull request merged**
