### PR TITLE
Sync with what improbable's using in prod

### PR DESCRIPTION
**Pull request by petemounce**
After this merges
* I'll do a major-version bump since ansible 2.8 is possibly breaking for users.
* I'll update the changelog, push that, and tag 2.0.0.

Sound good? @hectcastro I'd like to invite a couple of other people from improbable to review - are you and azavea ok with that?

### CODE REVIEW

**Comment by hectcastro** [comment]
> Sound good? @hectcastro I'd like to invite a couple of other people from improbable to review - are you and azavea ok with that?

Yes. In all honesty, you all are contributing more to this role than we are. Perhaps we can work on transferring it to your org's GitHub account?

**Comment by petemounce** [comment]
> Yes. In all honesty, you all are contributing more to this role than we are. Perhaps we can work on transferring it to your org's GitHub account?

@hectcastro we'd be happy with that if you are :)

**Comment by hectcastro** [comment]
Cool. I will transfer ownership to you, then you can transfer it to a desired org (we usually run into issues trying to transfer from org to org).

**Comment by hectcastro** [comment]
Looks like you need to delete your fork (under `petemounce`) before I can transfer it to you.

**Comment by petemounce** [comment]
Done

**Pull request closed without merging**
